# Generated by Django 5.2.7 on 2026-03-10 18:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0009_remove_bookingrequest_experience_and_more'),
        ('payments', '0002_paymentlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_type', models.CharField(choices=[('customer_payment', 'Customer Payment'), ('platform_commission', 'Platform Commission'), ('host_earning', 'Host Earning'), ('refund', 'Refund'), ('payout', 'Host Payout')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('reference_id', models.CharField(help_text='e.g Razorpay Payment ID or Payout ID', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='marketplace.booking')),
            ],
        ),
    ]
