# Generated by Django 5.2.8 on 2026-05-12 06:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_ledgerentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='raw_response',
            field=models.JSONField(blank=True, help_text='Raw Razorpay API response for debugging', null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentlog',
            name='event_id',
            field=models.CharField(blank=True, help_text='Razorpay webhook event ID for deduplication', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('created', 'Created'), ('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('verification_failed', 'Verification Failed'), ('refunded', 'Refunded')], default='created', max_length=25),
        ),
        migrations.AddIndex(
            model_name='paymentlog',
            index=models.Index(fields=['event_id'], name='paymentlog_event_id_idx'),
        ),
    ]
