# Generated by Django 5.2.8 on 2026-05-18 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0028_gst_invoice_settlement'),
        ('payments', '0004_payment_cleanup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_year', models.CharField(help_text='e.g. 25-26', max_length=7, unique=True)),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Invoice Counter',
                'verbose_name_plural': 'Invoice Counters',
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='base_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Per-person-per-day price at booking time', max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='cgst_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='gst_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='GST rate at booking time, e.g. 5.00', max_digits=5),
        ),
        migrations.AddField(
            model_name='payment',
            name='igst_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='invoice_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='invoice_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='place_of_supply',
            field=models.CharField(blank=True, help_text='Customer state / place of supply', max_length=100),
        ),
        migrations.AddField(
            model_name='payment',
            name='sac_code',
            field=models.CharField(blank=True, default='998555', max_length=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='sgst_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='subtotal_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='base × guests × days', max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='tax_currency',
            field=models.CharField(default='INR', max_length=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='tax_label',
            field=models.CharField(blank=True, help_text='e.g. GST @ 5%', max_length=50),
        ),
        migrations.AddField(
            model_name='payment',
            name='taxable_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='subtotal − discount', max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='total_payable_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='taxable + tax = Razorpay amount', max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='total_tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(db_index=True, max_length=30, unique=True)),
                ('invoice_date', models.DateField()),
                ('financial_year', models.CharField(help_text='e.g. 25-26', max_length=7)),
                ('supplier_name', models.CharField(max_length=255)),
                ('supplier_gstin', models.CharField(blank=True, max_length=15)),
                ('supplier_address', models.TextField(blank=True)),
                ('supplier_state', models.CharField(blank=True, max_length=100)),
                ('supplier_state_code', models.CharField(blank=True, max_length=5)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(blank=True, max_length=20)),
                ('customer_billing_address', models.TextField(blank=True)),
                ('customer_gstin', models.CharField(blank=True, max_length=15)),
                ('sac_code', models.CharField(default='998555', max_length=10)),
                ('service_description', models.TextField()),
                ('taxable_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gst_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cgst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sgst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('igst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_tax_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=255)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=255)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='invoices/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generated', 'Generated'), ('sent', 'Sent'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='marketplace.booking')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='payments.payment')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'ordering': ['-invoice_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VendorSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_total_paid', models.DecimalField(decimal_places=2, help_text='Total paid by customer incl. GST', max_digits=10)),
                ('taxable_amount', models.DecimalField(decimal_places=2, help_text='Pre-tax base amount', max_digits=10)),
                ('gst_amount_collected', models.DecimalField(decimal_places=2, help_text='GST portion collected from customer', max_digits=10)),
                ('routeless_commission', models.DecimalField(decimal_places=2, help_text='Platform fee on taxable amount', max_digits=10)),
                ('vendor_payout_amount', models.DecimalField(decimal_places=2, help_text='Amount payable to vendor', max_digits=10)),
                ('payout_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('payout_date', models.DateTimeField(blank=True, null=True)),
                ('internal_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_settlement', to='marketplace.booking')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vendor Settlement',
                'verbose_name_plural': 'Vendor Settlements',
                'ordering': ['-created_at'],
            },
        ),
    ]
