# Generated by Django 6.0.2 on 2026-02-23 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_hostrequest_experienceavailabilityblock'),
    ]

    operations = [
    ]
from django.db import migrations
from django.utils.text import slugify


def backfill_location_fk(apps, schema_editor):
    Experience = apps.get_model("marketplace", "Experience")
    Location = apps.get_model("marketplace", "Location")

    for exp in Experience.objects.all().iterator():
        raw = (exp.location or "").strip()
        if not raw or exp.location_fk_id:
            continue

        raw_lower = raw.lower()

        # 1) Exact name match
        loc = Location.objects.filter(name__iexact=raw).first()

        # 2) Slug match (handles "new-delhi" style text)
        if not loc:
            loc = Location.objects.filter(slug__iexact=slugify(raw)).first()

        # 3) Contains match (tolerant for "Rishikesh, Uttarakhand")
        if not loc:
            all_locs = Location.objects.all()
            for candidate in all_locs:
                cname = (candidate.name or "").strip().lower()
                if cname and (cname in raw_lower or raw_lower in cname):
                    loc = candidate
                    break

        # Save if matched
        if loc:
            exp.location_fk_id = loc.id
            exp.save(update_fields=["location_fk"])


def reverse_backfill_location_fk(apps, schema_editor):
    # Safe reverse: copy FK name back to text where possible
    Experience = apps.get_model("marketplace", "Experience")

    for exp in Experience.objects.select_related("location_fk").all().iterator():
        if exp.location_fk_id and (not exp.location or not exp.location.strip()):
            exp.location = exp.location_fk.name
            exp.save(update_fields=["location"])


class Migration(migrations.Migration):

    dependencies = [
    ('marketplace', '0002_hostrequest_experienceavailabilityblock'),
]

    operations = [
        migrations.RunPython(backfill_location_fk, reverse_backfill_location_fk),
    ]