# Generated by Django 6.0.2 on 2026-02-23 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_backfill_experience_location_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='location_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='experiences', to='marketplace.location'),
        ),
    ]
