# Generated by Django 6.0.2 on 2026-02-23 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_experience_location_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='category_details',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
