# Generated by Django 6.0.2 on 2026-02-23 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_experience_category_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='category_details',
        ),
        migrations.AddField(
            model_name='experience',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
