# Generated by Django 6.0.2 on 2026-02-24 10:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_remove_experience_category_details_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('subtitle', models.TextField(blank=True)),
                ('badge_text', models.CharField(blank=True, help_text='e.g., Curated Mountain Experiences', max_length=120)),
                ('badge_icon', models.CharField(blank=True, help_text='Bootstrap icon class, e.g. bi bi-stars or bi bi-camera-video', max_length=60)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10)),
                ('image', models.ImageField(blank=True, help_text='Required for image slides.', null=True, upload_to='hero_slides/images/')),
                ('video', models.FileField(blank=True, help_text='Required for video slides.', null=True, upload_to='hero_slides/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'ogg'])])),
                ('video_poster', models.ImageField(blank=True, help_text='Recommended poster image for video slide.', null=True, upload_to='hero_slides/posters/')),
                ('cta_primary_label', models.CharField(blank=True, max_length=60)),
                ('cta_primary_url', models.CharField(blank=True, help_text='Use absolute or relative URL, e.g. /listings/ or /listings/?category=Adventure', max_length=255)),
                ('cta_secondary_label', models.CharField(blank=True, max_length=60)),
                ('cta_secondary_url', models.CharField(blank=True, help_text='Use absolute or relative URL', max_length=255)),
                ('interval_ms', models.PositiveIntegerField(default=5000, help_text='Per-slide interval in milliseconds')),
                ('overlay_opacity_top', models.DecimalField(decimal_places=2, default=0.55, max_digits=3)),
                ('overlay_opacity_bottom', models.DecimalField(decimal_places=2, default=0.82, max_digits=3)),
                ('show_search_card', models.BooleanField(default=False, help_text='Enable the large search card on this slide (usually only first slide).')),
                ('show_trust_chips', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero Slide',
                'verbose_name_plural': 'Hero Slides',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
