# Generated by Django 5.2.7 on 2026-03-11 04:02

import marketplace.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0015_experience_is_flagged_experience_is_hidden_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experienceimage',
            name='image',
            field=models.ImageField(upload_to='experiences/', validators=[marketplace.models.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='hostverification',
            name='government_id',
            field=models.ImageField(upload_to='host_ids/', validators=[marketplace.models.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='hostverification',
            name='selfie',
            field=models.ImageField(upload_to='host_selfie/', validators=[marketplace.models.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='location',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='locations/', validators=[marketplace.models.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='profiles/', validators=[marketplace.models.validate_image_file]),
        ),
    ]
