# Generated by Django 5.2.7 on 2026-03-11 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0018_activityfeed_userevent_userpreference'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicPricingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('WEEKEND', 'Weekend Premium'), ('HOLIDAY', 'Holiday Premium'), ('SURGE', 'High Demand Surge'), ('DISCOUNT', 'Low Demand Discount')], max_length=20)),
                ('multiplier', models.DecimalField(decimal_places=2, help_text='e.g., 1.25 for a 25% increase', max_digits=4)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_rules', to='marketplace.experience')),
            ],
        ),
        migrations.CreateModel(
            name='DemandSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('search_count', models.PositiveIntegerField(default=0)),
                ('booking_attempts', models.PositiveIntegerField(default=0)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demand_signals', to='marketplace.experience')),
            ],
            options={
                'unique_together': {('experience', 'date')},
            },
        ),
    ]
