# Generated by Django 6.0.2 on 2026-03-13 06:21

import django.db.models.deletion
import marketplace.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0019_dynamicpricingrule_demandsignal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('payment_processing', 'Payment Processing'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='hostverification',
            name='government_id',
            field=models.ImageField(blank=True, null=True, upload_to='host_ids/', validators=[marketplace.models.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='hostverification',
            name='selfie',
            field=models.ImageField(blank=True, null=True, upload_to='host_selfie/', validators=[marketplace.models.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='review',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='marketplace.booking'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(fields=('user', 'host', 'experience'), name='unique_conversation_per_user_host_experience'),
        ),
    ]
