# Generated by Django 5.2.8 on 2026-04-23 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0022_userprofile_government_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroslide',
            name='badge_text',
            field=models.CharField(blank=True, help_text='e.g., Featured Mountain Experiences', max_length=120),
        ),
    ]
