# Generated by Django 5.2.8 on 2026-05-11 05:41

import django.db.models.deletion
import marketplace.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0023_alter_heroslide_badge_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HostApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_type', models.CharField(choices=[('individual', 'Individual'), ('company', 'Company')], default='individual', max_length=20)),
                ('full_name_or_company_name', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chhattisgarh', 'Chhattisgarh'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('West Bengal', 'West Bengal'), ('Chandigarh', 'Chandigarh'), ('Delhi', 'Delhi'), ('Jammu and Kashmir', 'Jammu and Kashmir'), ('Ladakh', 'Ladakh'), ('Puducherry', 'Puducherry'), ('Andaman and Nicobar Islands', 'Andaman and Nicobar Islands'), ('Dadra and Nagar Haveli and Daman and Diu', 'Dadra and Nagar Haveli and Daman and Diu'), ('Lakshadweep', 'Lakshadweep')], max_length=100)),
                ('host_bio', models.TextField(blank=True)),
                ('profile_photo_or_logo', models.ImageField(blank=True, null=True, upload_to='host_applications/photos/', validators=[marketplace.models.validate_image_file])),
                ('pan_number', models.CharField(blank=True, max_length=10)),
                ('government_id_proof', models.FileField(blank=True, upload_to='host_applications/govt_ids/', validators=[marketplace.models.validate_document_file])),
                ('police_verification_certificate', models.FileField(blank=True, upload_to='host_applications/police_certs/', validators=[marketplace.models.validate_document_file])),
                ('police_verification_issue_date', models.DateField(blank=True, null=True)),
                ('bank_account_holder_name', models.CharField(blank=True, max_length=255)),
                ('bank_name', models.CharField(blank=True, max_length=255)),
                ('account_number', models.CharField(blank=True, max_length=30)),
                ('ifsc_code', models.CharField(blank=True, max_length=11)),
                ('gst_number', models.CharField(blank=True, max_length=15)),
                ('msme_udyam_number', models.CharField(blank=True, max_length=30)),
                ('authorized_person_name', models.CharField(blank=True, max_length=255)),
                ('business_address', models.TextField(blank=True)),
                ('declaration_accepted', models.BooleanField(default=False)),
                ('verification_status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('more_info', 'More Info Required'), ('verified', 'Verified'), ('doc_expired', 'Document Expired'), ('suspended', 'Suspended'), ('rejected', 'Rejected')], db_index=True, default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Admin notes for rejection/more-info reasons.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='host_application', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Host Application',
                'verbose_name_plural': 'Host Applications',
                'ordering': ['-submitted_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ListingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('property_proof', 'Property Proof'), ('tourism_registration', 'Tourism Registration'), ('fssai_registration', 'FSSAI Registration'), ('driving_licence', 'Driving Licence'), ('vehicle_rc', 'Vehicle RC'), ('vehicle_insurance', 'Vehicle Insurance'), ('safety_declaration', 'Safety Declaration'), ('safety_certificate', 'Safety Certificate')], max_length=30)),
                ('document_file', models.FileField(upload_to='listing_documents/', validators=[marketplace.models.validate_document_file])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_documents', to='marketplace.experience')),
            ],
            options={
                'verbose_name': 'Listing Document',
                'verbose_name_plural': 'Listing Documents',
                'unique_together': {('experience', 'document_type')},
            },
        ),
    ]
