# Generated by Django 5.2.8 on 2026-05-11 11:44

import marketplace.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0025_alter_experienceimage_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Admin feedback for rejection/more-info/paused reasons.'),
        ),
        migrations.AddField(
            model_name='experience',
            name='cancellation_policy_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='experience',
            name='category_details',
            field=models.JSONField(blank=True, default=dict, help_text='Structured category-specific field data.'),
        ),
        migrations.AddField(
            model_name='experience',
            name='experience_highlights',
            field=models.TextField(blank=True, help_text='Key highlights of the experience, one per line.'),
        ),
        migrations.AddField(
            model_name='experience',
            name='listing_declaration_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='experience',
            name='listing_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('more_info', 'More Info Required'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paused', 'Paused'), ('doc_expired', 'Expired Documents')], db_index=True, default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='experience',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='what_is_included',
            field=models.JSONField(blank=True, default=list, help_text='List of items included (e.g. Food, Guide, Stay, Equipment)'),
        ),
        migrations.AddField(
            model_name='experience',
            name='what_is_not_included',
            field=models.JSONField(blank=True, default=list, help_text='List of items not included (e.g. Personal expenses, Meals)'),
        ),
        migrations.AlterField(
            model_name='experienceimage',
            name='image',
            field=models.ImageField(upload_to='experiences/', validators=[marketplace.models.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='hostverification',
            name='government_id',
            field=models.ImageField(blank=True, null=True, upload_to='host_ids/', validators=[marketplace.models.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='hostverification',
            name='selfie',
            field=models.ImageField(blank=True, null=True, upload_to='host_selfie/', validators=[marketplace.models.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='listingdocument',
            name='document_type',
            field=models.CharField(choices=[('property_proof', 'Property Proof'), ('tourism_registration', 'Tourism Registration'), ('fssai_registration', 'FSSAI Registration'), ('driving_licence', 'Driving Licence'), ('vehicle_rc', 'Vehicle RC'), ('vehicle_insurance', 'Vehicle Insurance'), ('safety_declaration', 'Safety Declaration'), ('safety_certificate', 'Safety Certificate'), ('trekking_permit', 'Trekking Permit'), ('guide_certificate', 'Guide Certificate'), ('emergency_plan', 'Emergency Plan'), ('permission_authorization', 'Permission / Authorization'), ('safari_permit', 'Safari Permit'), ('community_authorization', 'Community Authorization')], max_length=30),
        ),
        migrations.AlterField(
            model_name='location',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='locations/', validators=[marketplace.models.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='government_id',
            field=models.ImageField(blank=True, null=True, upload_to='govt_ids/', validators=[marketplace.models.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='profiles/', validators=[marketplace.models.validate_image_file]),
        ),
    ]
