# Generated by Django 5.2.8 on 2026-05-17 11:54

import django.core.validators
import django.db.models.deletion
import marketplace.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0026_experience_redesign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experienceimage',
            name='image',
            field=models.ImageField(upload_to='experiences/', validators=[marketplace.models.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='hostverification',
            name='government_id',
            field=models.ImageField(blank=True, null=True, upload_to='host_ids/', validators=[marketplace.models.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='hostverification',
            name='selfie',
            field=models.ImageField(blank=True, null=True, upload_to='host_selfie/', validators=[marketplace.models.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='location',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='locations/', validators=[marketplace.models.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='government_id',
            field=models.ImageField(blank=True, null=True, upload_to='govt_ids/', validators=[marketplace.models.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='profiles/', validators=[marketplace.models.validate_image_file]),
        ),
        migrations.CreateModel(
            name='ExperienceVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='experiences/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'webm']), marketplace.models.validate_video_file])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='marketplace.experience')),
            ],
        ),
    ]
