# Generated by Django 5.2.8 on 2026-05-18 18:47

import django.db.models.deletion
import marketplace.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0028_gst_invoice_settlement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='checked_in_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='checked_in_by',
            field=models.ForeignKey(blank=True, help_text='Host who verified check-in', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkins_performed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='checkin_attempt_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='checkin_code',
            field=models.CharField(blank=True, db_index=True, help_text='6-digit code for host verification', max_length=6),
        ),
        migrations.AddField(
            model_name='booking',
            name='checkin_method',
            field=models.CharField(blank=True, help_text='manual_code or qr_scan', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='checkin_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='checkin_status',
            field=models.CharField(choices=[('not_checked_in', 'Not Checked In'), ('checked_in', 'Checked In'), ('completed', 'Completed'), ('no_show', 'No Show')], default='not_checked_in', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='checkin_token',
            field=models.UUIDField(blank=True, db_index=True, default=None, help_text='Secure UUID token for QR-based verification', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='last_checkin_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('payment_processing', 'Payment Processing'), ('confirmed', 'Confirmed'), ('checked_in', 'Checked In'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('no_show', 'No Show')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='experienceimage',
            name='image',
            field=models.ImageField(upload_to='experiences/', validators=[marketplace.models.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='hostverification',
            name='government_id',
            field=models.ImageField(blank=True, null=True, upload_to='host_ids/', validators=[marketplace.models.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='hostverification',
            name='selfie',
            field=models.ImageField(blank=True, null=True, upload_to='host_selfie/', validators=[marketplace.models.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='location',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='locations/', validators=[marketplace.models.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='government_id',
            field=models.ImageField(blank=True, null=True, upload_to='govt_ids/', validators=[marketplace.models.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='profiles/', validators=[marketplace.models.validate_image_file]),
        ),
    ]
