import logging
from django.core.mail import EmailMultiAlternatives
from django.template.loader import render_to_string
from django.utils.html import strip_tags
from django.conf import settings

logger = logging.getLogger(__name__)


# -------------------------------------------------------------------
# Sender resolution
# -------------------------------------------------------------------
def get_sender_email(purpose):
    """
    Return the sender address for a given email purpose.

    Looks up ``settings.ROUTELESS_EMAILS`` and falls back to
    ``settings.DEFAULT_FROM_EMAIL`` for unknown purposes.

    Valid purposes: marketing, booking, admin, general, partners,
    support, ankit, harshit.
    """
    emails_map = getattr(settings, "ROUTELESS_EMAILS", {})
    return emails_map.get(purpose, getattr(settings, "DEFAULT_FROM_EMAIL", "hello@therouteless.com"))


# -------------------------------------------------------------------
# Centralized email helper
# -------------------------------------------------------------------
def send_routeless_email(purpose, subject, to, template_name=None, context=None,
                         plain_body=None, reply_to=None):
    """
    Send an email using the correct sender address for *purpose*.

    Parameters
    ----------
    purpose : str
        One of the keys in ``settings.ROUTELESS_EMAILS``
        (e.g. "booking", "support", "marketing").
    subject : str
        Email subject line.
    to : list[str]
        Recipient email addresses.
    template_name : str, optional
        Path to an HTML template.  If provided, the template is rendered
        and attached as the HTML alternative.
    context : dict, optional
        Context dict passed to the template.
    plain_body : str, optional
        Plain-text body.  If *template_name* is given and *plain_body* is
        not, a plain-text version is auto-generated by stripping HTML.
    reply_to : list[str], optional
        Reply-To addresses.  Defaults to the sender address.
    """
    from_email = get_sender_email(purpose)

    if reply_to is None:
        reply_to = [from_email]

    context = context or {}
    if "site_url" not in context:
        context["site_url"] = getattr(settings, "SITE_URL", "http://127.0.0.1:8080")

    try:
        if template_name:
            html_content = render_to_string(template_name, context)
            text_content = plain_body or strip_tags(html_content)
        else:
            html_content = None
            text_content = plain_body or ""

        email = EmailMultiAlternatives(
            subject=subject,
            body=text_content,
            from_email=from_email,
            to=to,
            reply_to=reply_to,
        )

        if html_content:
            email.attach_alternative(html_content, "text/html")

        email.send(fail_silently=True)

    except Exception as e:
        logger.error(
            "Failed to send email (purpose=%s, template=%s, to=%s): %s",
            purpose, template_name, to, e,
        )


# -------------------------------------------------------------------
# Legacy helper kept for internal use — now delegates to
# send_routeless_email() with an explicit purpose.
# -------------------------------------------------------------------
def _send_html_email_safe(subject, template_name, context, recipient_list,
                          purpose="general", reply_to=None):
    """
    Backward-compatible wrapper.  New code should prefer
    ``send_routeless_email()`` directly.
    """
    send_routeless_email(
        purpose=purpose,
        subject=subject,
        to=recipient_list,
        template_name=template_name,
        context=context,
        reply_to=reply_to,
    )


# -------------------------------------------------------------------
# Booking emails  →  purpose = "booking"  →  tribe@therouteless.com
# -------------------------------------------------------------------
def send_booking_created_email(booking):
    """
    Sent to the traveler immediately when a booking request is created.
    """
    subject = f"Booking Request Received - {booking.experience.title}"
    context = {
        'traveler_name': booking.traveler_name,
        'experience': booking.experience,
        'booking': booking,
    }
    _send_html_email_safe(
        subject, 'emails/booking_confirmation.html', context,
        [booking.traveler_email],
        purpose="booking",
    )

def send_payment_success_email(booking):
    """
    Sent to the traveler when payment is successful and booking is confirmed.
    """
    subject = f"Booking Confirmed! - {booking.experience.title}"
    context = {
        'traveler_name': booking.traveler_name,
        'experience': booking.experience,
        'booking': booking,
    }
    _send_html_email_safe(
        subject, 'emails/payment_success.html', context,
        [booking.traveler_email],
        purpose="booking",
    )

def send_host_new_booking_email(booking):
    """
    Sent to the host when a new booking is confirmed.
    """
    host = booking.experience.host
    if not host or not host.email:
        return

    subject = f"New Booking Confirmed - {booking.experience.title}"
    context = {
        'host': host,
        'experience': booking.experience,
        'booking': booking,
    }
    _send_html_email_safe(
        subject, 'emails/host_new_booking.html', context,
        [host.email],
        purpose="booking",
    )

def send_booking_status_update_email(booking):
    """
    Sent to the traveler when the host manually changes the booking status 
    (e.g., Completed, Cancelled). Uses plain-text for now.
    """
    subject = f"Update on your booking for {booking.experience.title}"
    message = f"""Hi {booking.traveler_name},

The status of your booking for {booking.experience.title} has been updated.

New Status: {booking.booking_status}

Thank you,
The Routeless Team
"""
    send_routeless_email(
        purpose="booking",
        subject=subject,
        to=[booking.traveler_email],
        plain_body=message,
        reply_to=[get_sender_email("support")],
    )

def send_payment_failed_email(booking):
    """
    Trigger the payment failure template if a retry loop causes issues.
    """
    subject = f"Payment Action Required - {booking.experience.title}"
    context = {
        'traveler_name': booking.traveler_name,
        'experience': booking.experience,
        'booking': booking,
    }
    _send_html_email_safe(
        subject, 'emails/payment_failed.html', context,
        [booking.traveler_email],
        purpose="booking",
        reply_to=[get_sender_email("support")],
    )

def send_review_request_email(booking):
    """
    Sent to the traveler after their booking is completed, asking for a review.
    """
    subject = f"How was your trip? - {booking.experience.title}"
    context = {
        'traveler_name': booking.traveler_name,
        'experience': booking.experience,
        'booking': booking,
    }
    _send_html_email_safe(
        subject, 'emails/review_request.html', context,
        [booking.traveler_email],
        purpose="booking",
    )


# -------------------------------------------------------------------
# Support / account emails  →  purpose = "support"
#                              →  support@therouteless.com
# -------------------------------------------------------------------
def send_otp_email(user, otp_code):
    """
    Send OTP code for email login.
    """
    subject = "Your Routeless Login OTP"
    message = (
        f"Hello {user.username},\n\n"
        f"Your login code is: {otp_code}\n\n"
        "This code will expire in 5 minutes.\n"
        "If you did not request this, please ignore."
    )
    send_routeless_email(
        purpose="support",
        subject=subject,
        to=[user.email],
        plain_body=message,
    )


# -------------------------------------------------------------------
# General notifications  →  purpose = "general"
#                          →  hello@therouteless.com
# -------------------------------------------------------------------
def send_new_message_email(message, recipient):
    """
    Sent to the recipient of a new message.
    """
    subject = f"New Message - {message.conversation.experience.title}"
    context = {
        'recipient_name': recipient.username,
        'sender_name': message.sender.username,
        'experience': message.conversation.experience,
        'message_text': message.text,
    }
    _send_html_email_safe(
        subject, 'emails/new_message.html', context,
        [recipient.email],
        purpose="general",
    )

def send_new_review_email(review):
    """
    Sent to the host when a new review is posted for their experience.
    """
    if not review.host or not review.host.email:
        return

    subject = f"New Review for {review.experience.title}"
    context = {
        'host_name': review.host.username,
        'reviewer_name': review.reviewer.username,
        'experience': review.experience,
        'rating': review.rating,
        'comment': review.comment,
    }
    _send_html_email_safe(
        subject, 'emails/new_review.html', context,
        [review.host.email],
        purpose="general",
    )
